CREATE TABLE mytable(
   sc_transfer_time string 
  ,`sauci`            string
  ,`sdndiv`           int
  ,`dmauction`        string 
  ,`crgnid`           string 
  ,`dmmonth`          int 
  ,`dmssllyr`         int 
  ,`dmstdesl`         int
  ,`dmwkyr`           int 
  ,`dmsalwk`          int 
  ,`dmweekday`        string 
  ,`ssleyr`           int 
  ,`sdtesl`           int  
  ,`sfasdin`          int  
  ,`sdtesa`           int  
  ,`sdteab`           int
  ,`sdtevd`           int  
  ,`sdtere`           int 
  ,`sdtedp`           int  
  ,`sdtert`           int  
  ,`sdtecl`           int  
  ,`sdtepd`           int  
  ,`sdtecn`           int 
  ,`sdtein`           int
  ,`dmdtecr`          int  
  ,`dmdteso`          int  
  ,`shwpd`            string
  ,`sdtefo`           int 
  ,`dmsold`           string 
  ,`dmclosed`         string 
  ,`dmhighln`         string 
  ,`dmarb`            string 
  ,`dmvoid`           string 
  ,`dmtrantype`       string
  ,`dmsimreg`         string
  ,`dmsimdate`        int
  ,`dmsimcons`        string
  ,`dmsimsltyp`       string
  ,`dmsim2nd`         string
  ,`dmonlinebd`       string
  ,`dmmiles`          int 
  ,`dmcondtn`         string 
  ,`dmsalvage`        string
  ,`dmslcause`        string
  ,`dmsltitsts`       string
  ,`scode`            string 
  ,`sgroup`           string 
  ,`dmlfgroup`        string 
  ,`sflndr`           string 
  ,`ssale`            int 
  ,`slane`            int 
  ,`srun`             int 
  ,`stimes`           int 
  ,`stmrun`           Infeger
  ,`swo`              int 
  ,`sblu`             int 
  ,`dmmafs`           string
  ,`sser17`           string 
  ,`sadjusr`          string
  ,`dmwhich`          string 
  ,`dmmodelyr`        int 
  ,`dmmake`           string 
  ,`dmmodel`          string 
  ,`dmbody`           string 
  ,`dmjdcat`          string 
  ,`dmjdsubcat`       string 
  ,`scond`            string 
  ,`sannou`           string 
  ,`smiles`           int 
  ,`sslepr`           int
  ,`sfloor`           int
  ,`sbhigh`           double 
  ,`mstcym`           int  
  ,`dmmmrreg`         int  
  ,`dmnada`           double  
  ,`dmblkbk`          double
  ,`dmslacv`          double  
  ,`dmbusunit`        string
  ,`mid`              string
  ,`sexyn1`           string
  ,`sexyn2`           string
  ,`ageddays`         int  
  ,`agetopay`         int  
  ,`agetopayf`        string
  ,`sfafcat`          string
  ,`dmprctier`        int  
  ,`dmsellrnm`        string 
  ,`ssellr`           int 
  ,`dmsellsign`       int  
  ,`dmselrepid`       int  
  ,`suid`             int 
  ,`csuid`            string 
  ,`dmkeysel`         string
  ,`smega`            string
  ,`dmbuyernm`        string
  ,`sbuyer`           int  
  ,`sbysg`            int  
  ,`dmbuyrepid`       int  
  ,`buid`             int  
  ,`cbuid`            string
  ,`bmega`            string
  ,`dmcat`            string 
  ,`dmowner`          string 
  ,`dmmktseg`         string 
  ,`dmsalerep`        string
  ,`dmehwrit`         string 
  ,`dmtotfee`         double  
  ,`dmsellfee`        double  
  ,`dmsselfe`         double  
  ,`dmstilfe`         double  
  ,`dmbuyfeet`        double  
  ,`sbuyfe`           int  
  ,`dmcertfee`        double  
  ,`dmpostsale`       double  
  ,`dmreconfee`       double  
  ,`dmadminfee`       double  
  ,`dmmechfee`        double  
  ,`dmmechlabr`       double  
  ,`dmmechpart`       double  
  ,`dmmechims`        double  
  ,`dmmechsubl`       double  
  ,`dmpbfee`          double  
  ,`dmdetfee`         double  
  ,`dmtrimfee`        double  
  ,`dmpdr`            double  
  ,`dmtransprt`       double  
  ,`dmpeer`           string 
  ,`dmecrdate`        int  
  ,`dmecrlabr`        double 
  ,`dmecrpart`        double
  ,`dmecrdays`        int
  ,`dmabexp1`         string
  ,`dmabexp2`         string
  ,`dmabexp3`         string
  ,`dmabdisp`         string
  ,`stitle`           string
  ,`smsoti`           string 
  ,`stile`            string
  ,`strn`             string
  ,`sintn1`           string
  ,`sintn2`           string
  ,`ssubse`           string
  ,`stspsoc`          string
  ,`sselne`           double
  ,`sbuyne`           double
  ,`sselfe`           int  
  ,`stilfe`           int  
  ,`sprime`           int  
  ,`sdftfe`           int  
  ,`sentfe`           int  
  ,`sotsfe1`          int  
  ,`sadj2`            int  
  ,`sremar`           string
  ,`slseac`           string
  ,`ptime`            int 
  ,`pdate`            DATE  
  ,`procesd`          string 
  ,`sbody`            string 
  ,`saucin`           string
  ,`fagmcd`           string
  ,`fasplsle`         string
  ,`sflrty`           string
  ,`sintco`           string
  ,`scolor`           string 
  ,`smod15`           string 
  ,`seng`             string
  ,`stop`             string
  ,`s4x4`             string
  ,`sbuydisc`         double
  ,`sseldisc`         double  
  ,`dmovesfee`        double  
  ,`dmovebfee`        double  
  ,`svehic`           string 
  ,`dmvehtype`        string 
  ,`dmcstpcar`        double  
  ,`sprimcd`          string 
  ,`dmlightr`         string 
  ,`dmlighty`         string 
  ,`dmlightg`         string 
  ,`dmlightb`         string 
  ,`dmabsetb`         string
  ,`dmabadjm`         int  
  ,`sstk`             string
  ,`dmtransub`        string
  ,`sflragcy`         int  
  ,`dmagencyid`       string
  ,`dmagencynm`       string
  ,`dmsimbuyfe`       double
  ,`dmsource1`        string 
  ,`dmsource2`        string 
  ,`snock`            string
  ,`sdtets`           int  
  ,`sdtecs`           int  
  ,`dmd2sttl`         int  
  ,`dmd2dpst`         int  
  ,`dmmrecdt`         DATE  
  ,`dmcertflg`        string 
  ,`sopera`           int  
  ,`sab`              string 
  ,`sac`              string
  ,`sbags`            string
  ,`scc`              string
  ,`sel`              string
  ,`ses`              string
  ,`sew`              string
  ,`sint`             string 
  ,`spb`              string 
  ,`sps`              string 
  ,`sradio`           string 
  ,`srdefr`           string
  ,`stilt`            string
  ,`dmcondtn1`        double
  ,`schgs`            int 
  ,`sdtesi`           DATE  
  ,`dmfafrj3`         string
  ,`dmsalehid`        int 
  ,`dmsimsldt`        int 
  ,`dmsaldesc`        string
  ,`dmsalconsg`       string
  ,`dmsimstyp`        string
  ,`dmstrrun`         int
  ,`dmendrun`         int
  ,`dmsimlan`         int 
  ,`dmlandesc`        string
  ,`dmmultauct`       string
  ,`dmparkauct`       string
  ,`dmhostauct`       string
  ,`dmclntauct`       string
  ,`dmclntwo`         string 
  ,`dmhostwo`         int
  ,`dmpsiflg`         string 
  ,`dmnvehic`         string
  ,`dmnvehcls`        string
  ,`vextlitid`        string
  ,`voveid`           string
  ,`vhecmmiles`       int
  ,`vhrearaxle`       int
  ,`vhtrnspds`        string
  ,`vhwhlbase`        int
  ,`vemodel15`        string
  ,`kyovesmtf`        string
  ,`ovelid`           string
  ,`ovesldf`          string
  ,`oveusldf`         string
  ,`ovesaledt`        int 
  ,`ovesellrid`       int  
  ,`ovebuyerid`       int  
  ,`ovesslepr`        double
  ,`ovesmiles`        int  
  ,`dminsight`        string 
  ,`dmprecond`        double
  ,`dmpostcond`       double  
  ,`dmpostncon`       int  
  ,`dmpostcndt`       int  
  ,`dminspdays`       int  
  ,`dmfactdr`         int 
  ,`dmfactpadr`       string
  ,`dmfactpcty`       string 
  ,`dmfactplnm`       string 
  ,`dmfactplst`       string 
  ,`dmfactrpct`       double
  ,`dmslvgclam`       string 
  ,`dmslvgadj`        string 
  ,`dmslvgacv`        double
  ,`dmhighbid`        int
  ,`dmhightbid`       int
  ,`dmopsellr`        int
  ,`dmopcsuid`        string 
  ,`agetofund`        int
  ,`agetofundf`       string 
  ,`dmcrtypei`         string 
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'  lines terminated by '\n'
STORED AS TEXTFILE
LOCATION '/data/database/manheim/sales/*'
tblproperties ("skip.header.line.count"="1");
